import { HASH_CALCULATION_UTILS_HASH_ALGORITHM } from '@pashoo2/crypto-utilities';
export declare const SWARM_MESSAGE_ENCRYPTED_CACHE_DEFAULT_STORAGE_DATABASE_NAME = "___SWARM_MESSAGE_ENCRYPTED_CACHE_DB_DEFAULT";
export declare const SWARM_MESSAGE_ENCRYPTED_CACHE_DEFAULT_STORAGE_DATABASE_NAME_HASH = HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA384;
//# sourceMappingURL=swarm-message-encrypted-cache.const.d.ts.map