import { ESwarmStoreConnector } from 'classes/swarm-store-class/swarm-store-class.const';
import { ISwarmMessageBodyDeserialized, ISwarmMessageInstanceDecrypted } from '../../classes/swarm-message/swarm-message-constructor.types';
import { ESwarmStoreConnectorOrbitDbDatabaseType } from '../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connector-orbit-db/swarm-store-connector-orbit-db-subclasses/swarm-store-connector-orbit-db-subclass-database/swarm-store-connector-orbit-db-subclass-database.const';
import { IConnectionBridgeOptionsUser, IConnectionBridgeOptionsAuth } from '../../classes/connection-bridge/types/connection-bridge.types';
import { TNativeConnectionOptions } from 'classes/connection-bridge/types/connection-bridge.types';
import { TSwarmStoreDatabaseOptions } from 'classes/swarm-store-class/index';
import { IConnectionBridgeOptionsDefault, TConnectionBridgeStorageOptionsDefault } from '../../classes/connection-bridge/types/connection-bridge.types';
import { ISwarmMessagesDatabaseConnectOptionsSwarmMessagesCacheOptions } from '../../classes/swarm-messages-database/swarm-messages-database.types';
import { SwarmMessagesDatabaseCache } from '../../classes/swarm-messages-database/swarm-messages-database-subclasses/swarm-messages-database-cache/swarm-messages-database-cache';
import { ConstructorArgumentType } from '../../types/helper.types';
import { ISwarmMessagesDatabaseCacheConstructor } from '../../classes/swarm-messages-database/swarm-messages-database.types';
import { ISwarmMessagesDatabaseMessagesCollector, ISwarmMessagesDatabaseMessagesCollectorWithStoreMeta } from '../../classes/swarm-messages-database/swarm-messages-database.messages-collector.types';
import { SwarmMessagesDatabaseCacheWithEntitiesCount } from '../../classes/swarm-messages-database/swarm-messages-database-subclasses/swarm-messages-database-cache-with-entities-count/swarm-messages-database-cache-with-entities-count';
import { ISwarmMessagesStoreMeta } from '../../classes/swarm-messages-database/swarm-messages-database.messages-collector.types';
import { ISwarmStoreConnectorBasicWithEntriesCount, ISwarmStoreConnectorWithEntriesCount } from '../../classes/swarm-store-class/swarm-store-class-extended/swarm-store-class-with-entries-count/swarm-store-class-with-entries-count.types';
import { TSwarmStoreConnectorBasicFabric, TSwarmStoreDatabaseType } from '../../classes/swarm-store-class/swarm-store-class.types';
import { SerializerClass } from '../../classes/basic-classes/serializer-class';
import { TSwarmMessageSerialized } from '../../classes/swarm-message/swarm-message-constructor.types';
import { IConnectionBridgeOptionsByStorageOptions } from '../../classes/connection-bridge/types/connection-bridge.types-helpers/connection-bridge-storage-options.types.helpers';
export declare const CONNECT_TO_SWARM_AUTH_CREDENTIALS_SESSION_STORAGE_KEY = "key";
export declare const CONNECT_TO_SWARM_STORAGE_DEFAULT_MESSAGE_BODY: ISwarmMessageBodyDeserialized;
export declare const CONNECT_TO_SWARM_AUTH_CREDENTIALS_1: {
    login: string;
    password: string;
};
export declare const CONNECT_TO_SWARM_AUTH_CREDENTIALS_USEDID_1 = "02https://protocol-firebase-default-rtdb.firebaseio.com|dlGUW2tKOjZDYYjE4U25CMbaNCF3";
export declare const CONNECT_TO_SWARM_AUTH_CREDENTIALS_2: {
    login: string;
    password: string;
};
export declare const CONNECT_TO_SWARM_AUTH_CREDENTIALS_USEDID_2 = "02https://protocol-firebase-default-rtdb.firebaseio.com|f7Yy0au1vuM2e7c9PJSwmrliHyz2";
export declare enum CONNECT_TO_SWARM_AUTH_PROVIDERS {
    FIREBASE_WATCHA = "https://protocol-firebase-default-rtdb.firebaseio.com",
    FIREBASE_PRTOCOL = "https://protocol-firebase-central-default-rtdb.firebaseio.com"
}
export declare const CONNECT_TO_SWARM_STORAGE_PROVIDER_DEFAULT = ESwarmStoreConnector.OrbitDB;
export declare const CONNECT_TO_SWARM_DATABASE_MAIN_NAME: string;
export declare const CONNECT_TO_SWARM_DATABASE_MAIN: TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE>;
export declare const CONNECT_TO_SWARM_DATABASE_MAIN_2: TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE>;
export declare const CONNECT_TO_SWARM_DATABASES_DEFAULT: Array<TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE>>;
export declare const CONNECT_TO_SWARM_CONNECTION_USER_OPTIONS: IConnectionBridgeOptionsUser;
export declare const CONNECT_TO_SWARM_CONNECTION_STORAGE_OPTIONS: TConnectionBridgeStorageOptionsDefault<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED>;
export declare const CONNECT_TO_SWARM_CONNECTION_STORAGE_WITH_STORE_META_OPTIONS: IConnectionBridgeOptionsDefault<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, false, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>, ISwarmMessageInstanceDecrypted | TSwarmMessageSerialized, any, any, any, ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>>, TSwarmStoreConnectorBasicFabric<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>, ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>>>, any, any, ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>, ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseType<ESwarmStoreConnector.OrbitDB>>>, any>>['storage'];
export declare const CONNECT_TO_SWARM_CONNECTION_AUTH_OPTOINS: IConnectionBridgeOptionsAuth<false>;
export declare const CONNECT_TO_SWARM_CONNECTION_NATIVE_CONNECTION_OPTIONS: TNativeConnectionOptions<ESwarmStoreConnector.OrbitDB>;
export declare const CONNECT_TO_SWARM_CONNECTION_OPTIONS: IConnectionBridgeOptionsDefault<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, false>;
export declare const CONNECT_TO_SWARM_CONNECTION_WITH_STORE_META_OPTIONS: IConnectionBridgeOptionsByStorageOptions<typeof CONNECT_TO_SWARM_STORAGE_PROVIDER_DEFAULT, TSwarmMessageSerialized, false, InstanceType<typeof SerializerClass>, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, TSwarmStoreDatabaseOptions<typeof CONNECT_TO_SWARM_STORAGE_PROVIDER_DEFAULT, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED>, typeof CONNECT_TO_SWARM_CONNECTION_STORAGE_WITH_STORE_META_OPTIONS>;
declare const SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_INSTANCE: ISwarmMessagesDatabaseCacheConstructor<ESwarmStoreConnector, string, ESwarmStoreConnectorOrbitDbDatabaseType, import("classes/swarm-store-class/index").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, ESwarmStoreConnectorOrbitDbDatabaseType>, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollector<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted>, import("../../classes/swarm-messages-database/swarm-messages-database.types").ISwarmMessagesDatabaseCacheOptions<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollector<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted>>, SwarmMessagesDatabaseCache<ESwarmStoreConnector, string, ESwarmStoreConnectorOrbitDbDatabaseType, import("classes/swarm-store-class/index").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, ESwarmStoreConnectorOrbitDbDatabaseType>, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollector<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted>, import("../../classes/swarm-messages-database/swarm-messages-database.types").ISwarmMessagesDatabaseCacheOptions<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollector<ESwarmStoreConnector, ESwarmStoreConnectorOrbitDbDatabaseType, ISwarmMessageInstanceDecrypted>>>>;
export declare const CONNECTO_TO_SWARM_OPTIONS_SWARM_MESSAGES_DATABASE_CACHE_OPTIONS: ISwarmMessagesDatabaseConnectOptionsSwarmMessagesCacheOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED>, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollector<ESwarmStoreConnector.OrbitDB, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, ISwarmMessageInstanceDecrypted>, ConstructorArgumentType<typeof SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_INSTANCE>, InstanceType<typeof SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_INSTANCE>>;
declare const SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_WITH_STORE_META_INSTANCE: typeof SwarmMessagesDatabaseCacheWithEntitiesCount;
export declare const CONNECTO_TO_SWARM_OPTIONS_SWARM_MESSAGES_DATABASE_CACHE_WITH_STORE_META_OPTIONS: ISwarmMessagesDatabaseConnectOptionsSwarmMessagesCacheOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED>, ISwarmMessageInstanceDecrypted, ISwarmMessagesDatabaseMessagesCollectorWithStoreMeta<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, TSwarmStoreDatabaseOptions<ESwarmStoreConnector.OrbitDB, TSwarmMessageSerialized, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED>, ESwarmStoreConnectorOrbitDbDatabaseType.KEY_VALUE | ESwarmStoreConnectorOrbitDbDatabaseType.FEED, ISwarmMessageInstanceDecrypted, ISwarmMessagesStoreMeta>, ConstructorArgumentType<typeof SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_WITH_STORE_META_INSTANCE>, InstanceType<typeof SWARM_MESSAGES_DATABASE_CACHE_CONSTRUCTOR_WITH_STORE_META_INSTANCE>>;
export {};
//# sourceMappingURL=connect-to-swarm.const.d.ts.map