import { SWARM_MESSAGE_SUBCLASS_VALIDATOR_PAYLOAD_MAX_LENGTH_BYTES } from '../../../swarm-message-subclass-validator.const';

export const VALIDATE_MESSAGE_BODY_RAW_FORAMT_MIN_LENGTH = 50;

export const VALIDATE_MESSAGE_BODY_RAW_FORAMT_MAX_LENGTH = SWARM_MESSAGE_SUBCLASS_VALIDATOR_PAYLOAD_MAX_LENGTH_BYTES;
