import { ENCRYPTION_FORMAT_SUPPORTED } from '../data-sign-utils/main.data-sign-utils.const';

export enum HASH_CALCULATION_UTILS_HASH_ALHORITHM {
  SHA256 = 'SHA-256',
  SHA384 = 'SHA-384',
  SHA512 = 'SHA-512',
}

export const HASH_CALCULATION_UTILS_HASH_ALHORITHM_OUTPUT_STRING_LENGTH: {
  [key in HASH_CALCULATION_UTILS_HASH_ALHORITHM]: number;
} = {
  [HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA256]: 64,
  [HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA384]: 96,
  [HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA512]: 128,
};

export const HASH_CALCULATION_UTILS_DEFAULT_HASH_ALHORITHM =
  (ENCRYPTION_FORMAT_SUPPORTED as HASH_CALCULATION_UTILS_HASH_ALHORITHM) ||
  HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA256;
