export const HASH_CALCULATION_UTILS_HASH_ALHORITHM = {
  SHA256: 'SHA-256',
  SHA384: 'SHA-384',
  SHA512: 'SHA-512',
};

export const HASH_CALCULATION_UTILS_DEFAULT_HASH_ALHORITHM =
  HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA256;
