import { TTypedArrays } from 'types/main.types';

export type TPASSWORD_ENCRYPTION_SUPPORTED_PASSWORD_NATIVE_TYPES =
  | TTypedArrays
  | ArrayBuffer;

export type TPASSWORD_ENCRYPTION_SUPPORTES_SALT_NATIVE_TYPES =
  | TTypedArrays
  | ArrayBuffer;

export type TPASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT = JsonWebKey;

export type TPASSWORD_ENCRYPTION_KEY_IMPORT_NATIVE_SUPPORTED_TYPES = TPASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT;
