import { decodeStringUTF8ToArrayBuffer } from 'utils/string-encoding-utils';
import { TTypedArrays } from 'types/main.types';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_IMPORTED_FORMAT =
  'raw';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALHORITHM = 'PBKDF2';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_IS_KEY_EXTRACTABLE = false;

export const PASSWORD_ENCRYPTON_UTILS_KEY_USAGES = ['deriveBits', 'deriveKey'];

export const PASSWORD_ENCRYPTON_UTILS_KEY_HASH_ALHORITHM = 'SHA-512';

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS = 100000;

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_BITS_KEY_LENGTH_BYTES = 16;

export const SALT_DEFAULT_STRING = encodeURIComponent(`
    Xj5MsSyT3MhDFhmLnkbX
    9itWYr6DnVZDnl1ln3xB
    zuPnB8lf0T5HomRJZPPv
    nK1MMjWcUF6JR8qiPuCL
    E6Fib2Fz6N5yUOoQ57nz
    oOYLX4nnru86DYmctpq6
    beCXmgq5e0519Sm8AqO0
    Z8v316cKFm71FLh02OHQ
    C7bzl7iLKd7YOZswJNyI
    Rb9OLjMdhgsSCfZW0h7P
`);

export const SALT_DEFAULT_ARRAY_BUFFER = decodeStringUTF8ToArrayBuffer(
  SALT_DEFAULT_STRING
) as TTypedArrays;

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_BASE_KEY_CONFIG = {
  name: PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALHORITHM,
  hash: PASSWORD_ENCRYPTON_UTILS_KEY_HASH_ALHORITHM,
  salt: null,
  iterations: PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS,
};

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_NAME = 'AES-GCM';

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH = 512;

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_CONFIG = {
  name: PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_NAME,
  length: PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH,
};

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IS_EXPORTED = true;

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_USAGES = [
  'encrypt, decrypt',
];

export const PASSWORD_ENRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT =
  'jwk';
