import { TSecretStoreConfiguration } from 'classes/secret-storage-class/secret-storage-class.types';
import { SECRET_STORAGE_PROVIDERS_NAME } from 'classes/secret-storage-class/secret-storage-class.const';

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_PROVIDER =
  SECRET_STORAGE_PROVIDERS_NAME.LOCAL_FORAGE;

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_DATABASE_NAME =
  'CA_STORAGE_CURRENT_USER_CREDENTIALS';

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_CONFIGURATION: TSecretStoreConfiguration = {
  storageProviderName: CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_PROVIDER,
};

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_OPTIONS = {
  dbName: CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_DATABASE_NAME,
};
