import { STORAGE_PROVIDERS_NAME } from 'classes/storage-providers/storage-providers.const';
import { ISecretStoreConfiguration } from 'classes/secret-storage-class/secret-storage-class.types';

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_PROVIDER = STORAGE_PROVIDERS_NAME.LOCAL_FORAGE;

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_DATABASE_NAME = 'CA_STORAGE_CURRENT_USER_CREDENTIALS';

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_CONFIGURATION: ISecretStoreConfiguration = {
  storageProviderName: CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_PROVIDER,
};

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_OPTIONS = {
  dbName: CA_STORAGE_CURRENT_USER_CREDENTIALS_SECRET_STORAGE_DATABASE_NAME,
};

export const CA_STORAGE_CURRENT_USER_CREDENTIALS_SESSION_KEY = 'CA_STORAGE_CURRENT_USER_CREDENTIALS_SESSION_KEY';
