export enum EOrbitDbCRUDOperations {
  ADD = 'ADD',
  GET = 'GET',
  REMOVE = 'REMOVE',
  ITERATE = 'ITERATE',
}

export const SWARM_STORE_CONNECTOR_ORBIT_DB_SUBCLASS_DATABASE_QUEUED_OPERATIONS_DEFAULT_TIMEOUT_MS = 2000;

export const SWARM_STORE_CONNECTOR_ORBIT_DB_SUBCLASS_DATABASE_QUEUED_CRUD_OPERATIONS_TIMEOUTS_MS = {
  [EOrbitDbCRUDOperations.ADD]: 3000,
  [EOrbitDbCRUDOperations.GET]: 1000,
  [EOrbitDbCRUDOperations.REMOVE]: 1000,
  [EOrbitDbCRUDOperations.ITERATE]: 30000,
};
