export const CONST_VALUES_RESTRICTIONS_COMMON_URI_MAX_LENGTH = 200;

export const CONST_VALUES_RESTRICTIONS_COMMON_UUID_V4_MAX_LENGTH = 36;

export const CONST_VALUES_RESTRICTIONS_COMMON_UUID_V4_MIN_LENGTH = 36;
