import { STORAGE_PROVIDERS_NAME } from "../../../../storage-providers/storage-providers.const";
export const CA_IDENTITY_CREDENTIALS_STORAGE_NAME_OPTIONS_MAX_LENGTH = 30;
export const CA_IDENTITY_CREDENTIALS_STORAGE_NAME = '_CICS';
export const CA_IDENTITY_CREDENTIALS_STORAGE_VERSION = '01';
export const CA_IDENTITY_CREDENTIALS_STORAGE_FULL_NAME = `${CA_IDENTITY_CREDENTIALS_STORAGE_VERSION}${CA_IDENTITY_CREDENTIALS_STORAGE_NAME}`;
export const CA_IDENTITY_CREDENTIALS_STORAGE_STATUS = {
    NEW: 'NEW',
    CONNECTING: 'CONNECTING',
    CONNECTED: 'CONNECTED',
    CONNECTION_FAILED: 'CONNECTION FAILED',
    ERROR: 'ERROR',
    PENDING: 'PENDING',
    DISCONNECTED: 'disconnected',
};
export const CA_IDENTITY_CREDENTIALS_STORAGE_DATABASE_NAME = 'CA_IDENTITY_CREDENTIALS_STORAGE';
export const CA_IDENTITY_CREDENTIALS_STORAGE_CONFIGURATION = {
    storageProviderName: STORAGE_PROVIDERS_NAME.LOCAL_FORAGE,
    options: {
        dbName: CA_IDENTITY_CREDENTIALS_STORAGE_DATABASE_NAME,
    },
};
export const CA_IDENTITY_CREDENTIALS_STORAGE_READ_CACHE_CAPACITY = 300;
export const CA_IDENTITY_CREDENTIALS_STORAGE_READ_RAW_CACHE_CAPACITY = 2000;
//# sourceMappingURL=central-authority-storage-swarm-users-identity-credentials.const.js.map