import { ESwarmStoreConnector } from '../../../classes/swarm-store-class/swarm-store-class.const';
import { TConnectionBridgeOptionsAuthCredentials, IConnectionBridgeOptions } from '../../../classes/connection-bridge/types/connection-bridge.types';
import { TSwarmMessageSerialized } from '../../../classes/swarm-message/swarm-message-constructor.types';
import { TSwarmStoreDatabaseType, TSwarmStoreDatabaseOptions } from '../../../classes/swarm-store-class/swarm-store-class.types';
import { ISerializer } from '../../../types/serialization.types';
export declare function connectToSwarmWithDBOUtil<P extends ESwarmStoreConnector, T extends TSwarmMessageSerialized, DbType extends TSwarmStoreDatabaseType<P>, DBO extends TSwarmStoreDatabaseOptions<P, T, DbType>, SRLZR extends ISerializer>(options: IConnectionBridgeOptions<P, T, DbType, DBO, any, any, any, any, any, any, any, any, any, any, any, any, any, any, SRLZR>, credentials: TConnectionBridgeOptionsAuthCredentials): Promise<import("../../../classes/connection-bridge/connection-bridge-utils-fabrics/connection-bridge-class-fabrics/connection-bridge-with-dbo-class/connection-bridge-with-dbo-class").ConnectionBridgeWithDBOClassEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, string | import("../../../classes/swarm-message/swarm-message-constructor.types").TSwarmMessageInstance, import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType>, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, string, import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>, import("../../..").ISwarmMessageConstructorWithEncryptedCacheFabric, import("../../..").ISwarmMessageStoreAccessControlOptions<ESwarmStoreConnector, string, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreOptionsConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreOptionsConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, import("../../..").ISwarmStoreConnectorOrbitDbConnecectionBasicFabric<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, boolean, import("../../..").ISwarmMessageStoreOptionsWithConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreOptionsConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, string | import("../../../classes/swarm-message/swarm-message-constructor.types").TSwarmMessageInstance, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>, import("../../..").ISwarmMessageConstructorWithEncryptedCacheFabric, import("../../..").ISwarmMessageStoreAccessControlOptions<ESwarmStoreConnector, string, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>>>, import("../../../classes/connection-bridge/connection-bridge-utils-fabrics/connection-bridge-class-fabrics/connection-bridge-with-dbo-class/connection-bridge-with-dbo-class-fabric.types").IConnectionBridgeWithDatabaseOptionsClassAndDBListPeristentStorageAndSwarmMessageCountOptions<any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>, import("../../..").ISwarmMessageStoreWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreOptionsConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, string | import("../../../classes/swarm-message/swarm-message-constructor.types").TSwarmMessageInstance, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>, import("../../..").ISwarmMessageConstructorWithEncryptedCacheFabric, import("../../..").ISwarmMessageStoreAccessControlOptions<ESwarmStoreConnector, string, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>>, import("../../..").ISwarmMessageStoreOptionsWithConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreOptionsConnectorFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreProviderOptions<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, string | import("../../../classes/swarm-message/swarm-message-constructor.types").TSwarmMessageInstance, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>, import("../../..").ISwarmMessageConstructorWithEncryptedCacheFabric, import("../../..").ISwarmMessageStoreAccessControlOptions<ESwarmStoreConnector, string, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../..").TSwarmMessagesStoreGrantAccessCallback<ESwarmStoreConnector, string | import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, Record<string, unknown>>>>> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreWithConnector<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../..").ISwarmStoreConnectorWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../..").ISwarmStoreConnectorOrbitDBConnectionOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, import("../../..").ISwarmStoreConnectorBasicWithEntriesCount<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>>>, import("../../../classes/connection-bridge/types/connection-bridge.types").ISwarmStoreDatabasesPersistentListFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, Record<string, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>>, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>, import("../../../classes/swarm-message-store/types/swarm-message-store-db-options.types").ISwarmMessageStoreConectorDbOptionsGrandAccessContextClassFabric<import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>>, import("../../../classes/connection-bridge/types/connection-bridge-swarm-fabrics.types").ISwarmMessageStoreConnectorDbOptionsClassFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, string, import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>, import("../../../classes/swarm-message-store/types/swarm-message-store-db-options.types").ISwarmMessageStoreConectorDbOptionsGrandAccessContextClassFabric<import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>>, never>, (serializer: ISerializer<any>) => import("../../../classes/connection-bridge/types/connection-bridge-swarm-fabrics.types").ISwarmMessageStoreConnectorDbOptionsClassFabric<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageInstanceDecrypted, import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}, string, import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>, import("../../../classes/swarm-message-store/types/swarm-message-store-db-options.types").ISwarmMessageStoreConectorDbOptionsGrandAccessContextClassFabric<import("../../../classes/swarm-message/swarm-message-constructor.types").ISwarmMessageConstructor, import("../../../types").ConstructorType<import("../../../classes/swarm-store-class/swarm-store-connectors/swarm-store-connetors.types").ISwarmStoreDBOGrandAccessCallbackBaseContext, any[]>>, never>, import("../../..").ISwarmMessageStoreEvents<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../../classes/swarm-store-class/swarm-store-class.types").TSwarmStoreOptionsOfDatabasesKnownList<ESwarmStoreConnector, string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType, import("../../..").ISwarmStoreConnectorOrbitDbDatabaseOptions<string, import("../../..").ESwarmStoreConnectorOrbitDbDatabaseType> & import("../../../classes/swarm-store-class/swarm-store-class.types").ISwarmStoreDatabaseBaseOptions & {
    provider: ESwarmStoreConnector;
}>, import("../../../types").IPFS, ISerializer<any>>>;
//# sourceMappingURL=connect-to-swarm-with-dbo-utils.d.ts.map