import { FILE_STORAGE_SERVICE_TYPE } from '../../filestorage-class.const';

export enum FILE_STORAGE_PROVIDER_EVENTS {
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  CONENCTION_ERROR = 'CONENCTION_ERROR',
}

export const FILE_STORAGE_PROVIDER_IPFS_IDENTIFIER = 'IPFS';

export const FILE_STORAGE_PROVIDER_IPFS_TYPE = FILE_STORAGE_SERVICE_TYPE.IPFS;

export const FILE_STORAGE_PROVIDER_IPFS_FILE_UPLOAD_TIMEOUT_MS = 180000;

export const FILE_STORAGE_PROVIDER_ROOT_PATH_DEFAULT = '/';
