import { HASH_CALCULATION_UTILS_HASH_ALHORITHM } from 'utils/hash-calculation-utils/hash-calculation-utils.const';

export const SECRET_STORAGE_CLASS_UTILS_LOGIN_HASH_ALG =
  HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA512;

export const SECRET_STORAGE_CLASS_UTILS_LOGIN_SALT =
  'FGJKFKGLKDFHJGKDFHGDFJKGHREIOUHGFNJFGHKJJHN930424780987';
