export const CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR = '2019';

export const CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR_MONTH = '01';

export const CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR_MONTH_DAY = '01';

export const CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_STRING_IN_UTC = `${CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR}-${CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR_MONTH}-${CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_YEAR_MONTH_DAY}T00:00:00.00Z`;

export const CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN = new Date(CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN_STRING_IN_UTC);

export let CONST_VALIDATION_VALUES_MESSAGING_DATE_MAX = new Date();

function setDateMax() {
    const d = new Date();

    d.setSeconds(d.getSeconds() + 1);
    CONST_VALIDATION_VALUES_MESSAGING_DATE_MAX = d;
}

setTimeout(setDateMax, 1000);

