import { 
    CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN,
    CONST_VALIDATION_VALUES_MESSAGING_DATE_MAX,
} from './const-validation-values-messaging-date';
import { getSecondsByMilliseconds } from 'utils/common-utils/common-utils-date-time';

export const CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MIN_MS = CONST_VALIDATION_VALUES_MESSAGING_DATE_MIN.getTime();

export const CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MIN_S = getSecondsByMilliseconds(CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MIN_MS);

export let CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_MS = CONST_VALIDATION_VALUES_MESSAGING_DATE_MAX.getTime();

export let CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_S = getSecondsByMilliseconds(CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_MS);

function setTimestampsMaxByDateMax() {
    CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_MS = CONST_VALIDATION_VALUES_MESSAGING_DATE_MAX.getTime();
    CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_S =  getSecondsByMilliseconds(CONST_VALIDATION_VALUES_TIMESTAMP_UNIX_MAX_MS);
}

setTimeout(setTimestampsMaxByDateMax, 1000);