import { FILE_STORAGE_SERVICE_TYPE } from '../../filestorage-class.const';

export const FILE_STORAGE_PROVIDER_HTTP_TYPE = FILE_STORAGE_SERVICE_TYPE.HTTP;

export const FILE_STORAGE_PROVIDER_HTTP_IDENTIFIER =
  'FILE_STORAGE_PROVIDER_HTTP_IDENTIFIER';
