import { HASH_CALCULATION_UTILS_HASH_ALHORITHM_OUTPUT_STRING_LENGTH } from 'utils/hash-calculation-utils/hash-calculation-utils.const';
export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_ID_MAX_LENGTH = 200;

export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_PASSWORD_MAX_LENGTH = 40;

export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_PASSWORD_MIN_LENGTH = 8;

// SHA-512 must be used for hashing
export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_PASSWORD_HASH_MIN_LENGTH =
  HASH_CALCULATION_UTILS_HASH_ALHORITHM_OUTPUT_STRING_LENGTH['SHA-512'];

export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_PASSWORD_HASH_MAX_LENGTH =
  HASH_CALCULATION_UTILS_HASH_ALHORITHM_OUTPUT_STRING_LENGTH['SHA-512'];

export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_NAME_MAX_LENGTH = 250;

export const SWARM_CHANNEL_BASE_PARTICIPANTS_MAX_USERS = 500;

export const SWARM_CHANNEL_BASE_BLACK_LIST_MAX_MEMBERS = 5000;

export const SWARM_CHANNEL_BASE_VALIDATOR_CHANNEL_DESCRIPTION_MAX_LENGTH = 5000;
