/** Declaration file generated by dts-gen */

declare module 'libp2p-websockets' {
  export = libp2p_websockets;

  declare function libp2p_websockets(...args: any[]): any;

  declare namespace libp2p_websockets {
    function isWebSockets(obj: any): void;
  }
}
