/** Declaration file generated by dts-gen */
declare module 'libp2p-tcp' {
  export = libp2p_tcp;

  declare function libp2p_tcp(...args: any[]): any;

  declare namespace libp2p_tcp {
    function isTCP(obj: any): void;
  }
}
