/** Declaration file generated by dts-gen */

declare module 'libp2p-stardust' {
  export = libp2p_stardust;

  function libp2p_stardust(...args: any[]): any;

  function isstardust(obj: any): void;

  libp2p_stardust.isstardust = isstardust;
}
