import { SECRET_STORAGE_PROVIDERS_NAME } from 'classes/secret-storage-class/secret-storage-class.const';

export const SAFE_STORAGE_STORAGE_NAME_COMMON_PREFIX = '__safe_storage__';

export const SAFE_STORAGE_STORAGE_APPEND_LOG_COMMON_POSTFIX = '__append_log';

export const SAFE_STORAGE_ATTEMPTS_TO_SAVE_DATA_TO_STORAGE = 4;

export const SAFE_STORAGE_DEFAULT_DUMP_INTERVAL_MS = 1000;

export const SAFE_STORAGE_MAX_ITEMS_APPEND_LOG = 200;

export const SAFE_STORAGE_DUMP_PROVIDERS = { ...SECRET_STORAGE_PROVIDERS_NAME };

export const SAFE_STORAGE_DUMP_PROVIDER_DEFAULT =
  SAFE_STORAGE_DUMP_PROVIDERS.LOCAL_STORAGE;

export enum ESAFE_STORAGE_PROVIDER_STATUS {
  NEW = 'NEW',
  CONNECTING_TO_STORAGE = 'CONNECTING_TO_STORAGE',
  CONNECTED_TO_STORAGE = 'CONNECTED_TO_STORAGE',
  WORKING_WITH_STORAGE = 'WORKING_WITH_STORAGE',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
}

export enum ESAFE_STORAGE_RETURN_TYPE {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  OBJECT = 'OBJECT',
}

export enum ESAFE_STORAGE_STORAGE_TYPE {
  KEY_VALUE = 'KEY_VALUE',
  APPEND_LOG = 'APPEND_LOG',
}

export const SAFE_STORAGE_APPEND_LOG_INITIAL_VALUE = [];

export const SAFE_STORAGE_KEY_VALUE_INITIAL_VALUE = {};

export const SAFE_STORAGE_APPEND_LOG_APPEND_DATA_INITIAL_VALUE = [];

export const SAFE_STORAGE_KEY_VALUE_APPEND_DATA_INITIAL_VALUE = {};
