import { HASH_CALCULATION_UTILS_HASH_ALHORITHM } from 'utils';
export const SWARM_MESSGAE_ENCRYPTED_CACHE_DEFAULT_STORAGE_DATABASE_NAME =
  '___SWARM_MESSGAE_ENCRYPTED_CACHE_DB_DEFAULT';

export const SWARM_MESSGAE_ENCRYPTED_CACHE_DEFAULT_STORAGE_DATABASE_NAME_HASH =
  HASH_CALCULATION_UTILS_HASH_ALHORITHM.SHA384;
