// export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_HOST =
//   'geochat-wrtc-start.herokuapp.com';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_HOST = '0.0.0.0'

// TODO export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL = 'wss';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL = 'ws';

// TODO export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_DELEGATE_API_PORT = '443';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_DELEGATE_API_PORT = '8080';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL_WS_START =
  'p2p-websocket-star';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL_WEBRTC_START =
  'p2p-webrtc-star';

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESS_BASE = `/dns4/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_HOST}/tcp/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_DELEGATE_API_PORT}/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL}`;
export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESS_WS = `/dns4/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_HOST}/tcp/13580/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL}`;
export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESS_WRTC = `/dns4/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_HOST}/tcp/13581/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL}`;

export const SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESSES = [
  `${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESS_WS}/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL_WS_START}`,
  `${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_MULTIADDRESS_WRTC}/${SWARM_CONNECTION_SUBCLASS_IPFS_CONFIG_SIGNAL_STAR_PROTOCOL_WEBRTC_START}`,
];
