import {
  CA_CRYPTO_KEY_PAIRS_ENCRYPTION_KEY_PAIR_NAME,
  CA_CRYPTO_KEY_PAIRS_SIGN_KEY_PAIR_NAME,
  CA_CRYPTO_KEY_PAIRS_SIGN_PUBLIC_KEY_NAME,
  CA_CRYPTO_KEY_PAIRS_ENCRYPTION_PUBLIC_KEY_NAME,
} from '../central-authority-utils/central-authority-util-crypto-keys';

export type TCACryptoKeyPairs = {
  [CA_CRYPTO_KEY_PAIRS_ENCRYPTION_KEY_PAIR_NAME]: CryptoKeyPair;
  [CA_CRYPTO_KEY_PAIRS_SIGN_KEY_PAIR_NAME]: CryptoKeyPair;
};

export type TCACryptoPubilicKeys = {
  [CA_CRYPTO_KEY_PAIRS_ENCRYPTION_PUBLIC_KEY_NAME]: CryptoKey;
  [CA_CRYPTO_KEY_PAIRS_SIGN_PUBLIC_KEY_NAME]: CryptoKey;
};
