export const SECRET_STORAGE_UNSET_MAX_ATTEMPTS = 3;

export const SECRET_STORAGE_PASSWORD_MIN_LENGTH = 6;

export const SECRET_STORAGE_LOGIN_MIN_LENGTH = 4;

export const SECRET_STORAGE_STATUS = {
  STOPPED: undefined,
  RUNNING: 'RUNNING',
  CONNECTING: 'CONNECTING',
  ERROR: 'ERROR',
};

export const SECRET_STORAGE_SESSION_KEY = 'SECRET_STORAGE_SESSION_KEY';
