export const CA_USER_IDENTITY_TYPE = 'string';

export const CA_USER_IDENTITY_UNIQUE_IDENTIFIER_MIN_LENGTH = 36;

export const CA_USER_IDENTITY_UNIQUE_IDENTIFIER_MAX_LENGTH = 36;

export const CA_USER_IDENTITY_AUTHORITY_IDENTIFIER_MIN_LENGTH = 36;

export const CA_USER_IDENTITY_AUTHORITY_IDENTIFIER_MAX_LENGTH = 36;

export const CA_USER_IDENTITY_MIN_LENGTH =
  CA_USER_IDENTITY_AUTHORITY_IDENTIFIER_MIN_LENGTH +
  CA_USER_IDENTITY_UNIQUE_IDENTIFIER_MIN_LENGTH;

export const CA_USER_IDENTITY_MAX_LENGTH =
  CA_USER_IDENTITY_AUTHORITY_IDENTIFIER_MAX_LENGTH +
  CA_USER_IDENTITY_UNIQUE_IDENTIFIER_MAX_LENGTH;

export const CA_USER_PASSWORD_TYPE = 'string';

export const CA_USER_PASSWORD_MIN_LENGTH = 6;

export const CA_AUTH_CREDENTIALS_USER_IDENTITY_PROP_NAME = 'userIdentity';

export const CA_AUTH_CREDENTIALS_USER_PASSWORD_PROP_NAME = 'password';
