export const CA_USER_IDENTITY_VERSION_CHARACTERS_COUNT = 2;

export const CA_USER_IDENTITY_PARSER_VERSIONS = {
  '01': '01',
};

export const CA_USER_IDENTITY_PARSER_VERSIONS_SUPPORTED = Object.values(
  CA_USER_IDENTITY_PARSER_VERSIONS
);

export const CA_USER_IDENTITY_AUTH_PROVIDER_IDENTIFIER_PROP_NAME =
  'authorityProviderURI';

export const CA_USER_IDENTITY_USER_UNIQUE_IDENTFIER_PROP_NAME =
  'userUniqueIdentifier';

export const CA_USER_IDENTITY_VERSION_PROP_NAME = 'version';

export const CA_USER_IDENTITY_VERSION_CURRENT =
  CA_USER_IDENTITY_PARSER_VERSIONS['01'];
