export const COMMON_VALUE_EVENT_EMITTER_METHOD_NAME_ON = 'on';

export const COMMON_VALUE_EVENT_EMITTER_METHOD_NAME_OFF = 'off';

export const COMMON_VALUE_EVENT_EMITTER_METHOD_NAME_UNSET_ALL_LISTENERS = 'removeAllListeners';