import { STORAGE_PROVIDERS_NAME } from "../storage-providers/storage-providers.const";
export const SAFE_STORAGE_STORAGE_NAME_COMMON_PREFIX = '__safe_storage__';
export const SAFE_STORAGE_STORAGE_APPEND_LOG_COMMON_POSTFIX = '__append_log';
export const SAFE_STORAGE_ATTEMPTS_TO_SAVE_DATA_TO_STORAGE = 4;
export const SAFE_STORAGE_DEFAULT_DUMP_INTERVAL_MS = 1000;
export const SAFE_STORAGE_DEFAULT_STORAGE_BUSY_TIMEOUT_MS = 10000;
export const SAFE_STORAGE_PARSE_DATA_ERROR_TRY_TO_DECODE = 'Unexpected token %';
export const SAFE_STORAGE_MAX_ITEMS_APPEND_LOG = 200;
export const SAFE_STORAGE_DUMP_PROVIDERS = Object.assign({}, STORAGE_PROVIDERS_NAME);
export const SAFE_STORAGE_DUMP_PROVIDER_DEFAULT = SAFE_STORAGE_DUMP_PROVIDERS.LOCAL_STORAGE;
export var ESAFE_STORAGE_PROVIDER_STATUS;
(function (ESAFE_STORAGE_PROVIDER_STATUS) {
    ESAFE_STORAGE_PROVIDER_STATUS["NEW"] = "NEW";
    ESAFE_STORAGE_PROVIDER_STATUS["CONNECTING_TO_STORAGE"] = "CONNECTING_TO_STORAGE";
    ESAFE_STORAGE_PROVIDER_STATUS["CONNECTED_TO_STORAGE"] = "CONNECTED_TO_STORAGE";
    ESAFE_STORAGE_PROVIDER_STATUS["READY"] = "READY";
    ESAFE_STORAGE_PROVIDER_STATUS["WORKING_WITH_STORAGE"] = "WORKING_WITH_STORAGE";
    ESAFE_STORAGE_PROVIDER_STATUS["DISCONNECTED"] = "DISCONNECTED";
    ESAFE_STORAGE_PROVIDER_STATUS["ERROR"] = "ERROR";
})(ESAFE_STORAGE_PROVIDER_STATUS || (ESAFE_STORAGE_PROVIDER_STATUS = {}));
export var ESAFE_STORAGE_RETURN_TYPE;
(function (ESAFE_STORAGE_RETURN_TYPE) {
    ESAFE_STORAGE_RETURN_TYPE["STRING"] = "STRING";
    ESAFE_STORAGE_RETURN_TYPE["NUMBER"] = "NUMBER";
    ESAFE_STORAGE_RETURN_TYPE["OBJECT"] = "OBJECT";
})(ESAFE_STORAGE_RETURN_TYPE || (ESAFE_STORAGE_RETURN_TYPE = {}));
export var ESAFE_STORAGE_STORAGE_TYPE;
(function (ESAFE_STORAGE_STORAGE_TYPE) {
    ESAFE_STORAGE_STORAGE_TYPE["KEY_VALUE"] = "KEY_VALUE";
    ESAFE_STORAGE_STORAGE_TYPE["APPEND_LOG"] = "APPEND_LOG";
})(ESAFE_STORAGE_STORAGE_TYPE || (ESAFE_STORAGE_STORAGE_TYPE = {}));
export const SAFE_STORAGE_APPEND_LOG_INITIAL_VALUE = [];
export const SAFE_STORAGE_KEY_VALUE_INITIAL_VALUE = {};
export const SAFE_STORAGE_APPEND_LOG_APPEND_DATA_INITIAL_VALUE = [];
export const SAFE_STORAGE_KEY_VALUE_APPEND_DATA_INITIAL_VALUE = {};
//# sourceMappingURL=safe-storage-class.const.js.map